"""Deterministic SYNTHETIC city generator.

*** ALL DATA HERE IS SYNTHETIC. It does not describe any real city. ***

Method
------
1. A hand-authored layout places 22 named nodes on a local km grid
   (x = east, y = north) around an arbitrary anchor coordinate.
2. A seeded ``random.Random(seed)`` adds small coordinate jitter.
3. 28 hand-authored road links become 56 directed edges (both directions).
   Road distance = straight-line distance x seeded detour factor (per road type),
   rounded UP; base time = distance / nominal road-type speed, rounded UP.
   Rounding up guarantees the geometry rules that keep A* admissible.
4. Each directed edge gets a seeded baseline vehicle count.

The only randomness comes from the local RNG, consumed in a fixed order, so the
same seed always yields byte-identical output.
"""

from __future__ import annotations

import math
import random
from typing import Any

from app.config import (
    BASELINE_UTILIZATION_RANGE,
    COORDINATE_JITTER_KM,
    DEFAULT_CONGESTION,
    DEFAULT_SEED,
    KM_PER_DEGREE_LAT,
    NETWORK_MAX_SPEED_KMH,
    ROAD_TYPE_PROFILES,
    SCENARIO_SCHEMA_VERSION,
    SYNTHETIC_ANCHOR_LAT,
    SYNTHETIC_ANCHOR_LON,
)
from app.network.builder import LoadedScenario, scenario_from_dict
from app.network.geo import haversine_km

# (node_id, name, node_type, x_km, y_km)
NODE_LAYOUT: tuple[tuple[str, str, str, float, float], ...] = (
    ("north_station", "North Station", "station", 0.5, 7.5),
    ("central_station", "Central Station", "station", 0.0, 0.0),
    ("east_hub", "East Hub", "terminal", 7.0, 0.5),
    ("west_hub", "West Hub", "terminal", -7.0, -0.5),
    ("airport", "Airport", "terminal", 15.0, -3.0),
    ("university", "University", "station", -4.0, 6.0),
    ("tech_park", "Tech Park", "station", 9.0, 6.0),
    ("industrial_zone", "Industrial Zone", "station", 6.0, -7.0),
    ("riverside", "Riverside", "station", -5.0, -5.0),
    ("market", "Market", "station", 1.5, -2.5),
    ("residential_north", "Residential North", "station", -2.0, 11.0),
    ("residential_south", "Residential South", "station", -1.0, -10.0),
    ("jct_northgate", "Northgate Junction", "intersection", 3.0, 4.0),
    ("jct_old_town", "Old Town Crossing", "intersection", -3.0, 2.0),
    ("jct_harbor_road", "Harbor Road Junction", "intersection", 4.0, -3.0),
    ("jct_ring_north", "Ring Road North", "intersection", 5.0, 9.0),
    ("jct_ring_south", "Ring Road South", "intersection", 3.0, -10.0),
    ("jct_airport", "Airport Interchange", "intersection", 11.0, -1.0),
    ("jct_mill_street", "Mill Street Junction", "intersection", -6.0, 1.0),
    ("jct_canal_bridge", "Canal Bridge", "intersection", -2.0, -4.0),
    ("jct_eastern_bypass", "Eastern Bypass", "intersection", 12.0, 3.0),
    ("jct_lakeside", "Lakeside Circle", "intersection", -8.0, 5.0),
)

# (node_a, node_b, road_type) — each link becomes two directed edges.
ROAD_LINKS: tuple[tuple[str, str, str], ...] = (
    # East–west trunk corridor (future platooning backbone)
    ("west_hub", "central_station", "trunk"),
    ("central_station", "east_hub", "trunk"),
    ("east_hub", "jct_airport", "trunk"),
    ("jct_airport", "airport", "trunk"),
    # Arterials
    ("north_station", "jct_northgate", "arterial"),
    ("jct_northgate", "east_hub", "arterial"),
    ("north_station", "central_station", "arterial"),
    ("central_station", "market", "arterial"),
    ("market", "jct_harbor_road", "arterial"),
    ("jct_harbor_road", "industrial_zone", "arterial"),
    ("jct_harbor_road", "jct_airport", "arterial"),
    ("jct_northgate", "tech_park", "arterial"),
    ("tech_park", "jct_eastern_bypass", "arterial"),
    ("jct_eastern_bypass", "airport", "arterial"),
    ("north_station", "jct_ring_north", "arterial"),
    ("jct_ring_north", "tech_park", "arterial"),
    ("university", "jct_old_town", "arterial"),
    ("jct_old_town", "central_station", "arterial"),
    ("residential_north", "north_station", "arterial"),
    ("residential_north", "university", "arterial"),
    ("industrial_zone", "jct_ring_south", "arterial"),
    ("jct_ring_south", "residential_south", "arterial"),
    # Local streets
    ("university", "jct_lakeside", "local"),
    ("jct_lakeside", "jct_mill_street", "local"),
    ("jct_mill_street", "west_hub", "local"),
    ("riverside", "jct_canal_bridge", "local"),
    ("jct_canal_bridge", "market", "local"),
    ("jct_canal_bridge", "residential_south", "local"),
)

PROVENANCE = (
    "SYNTHETIC — generated by app.network.synthetic_city. Names, coordinates, "
    "distances, capacities and traffic counts are invented for prototyping and do "
    "not describe any real city or measured traffic."
)


def _ceil_to(value: float, decimals: int) -> float:
    factor = 10**decimals
    return math.ceil(value * factor) / factor


def _km_to_latlon(x_km: float, y_km: float) -> tuple[float, float]:
    lat = SYNTHETIC_ANCHOR_LAT + y_km / KM_PER_DEGREE_LAT
    lon = SYNTHETIC_ANCHOR_LON + x_km / (KM_PER_DEGREE_LAT * math.cos(math.radians(SYNTHETIC_ANCHOR_LAT)))
    return round(lat, 6), round(lon, 6)


def generate_synthetic_city_dict(seed: int = DEFAULT_SEED) -> dict[str, Any]:
    """Return a complete scenario dict for the synthetic city."""
    if isinstance(seed, bool) or not isinstance(seed, int):
        raise TypeError("seed must be an int")
    rng = random.Random(seed)

    nodes: list[dict[str, Any]] = []
    coords: dict[str, tuple[float, float]] = {}
    for node_id, name, node_type, x_km, y_km in NODE_LAYOUT:
        jx = rng.uniform(-COORDINATE_JITTER_KM, COORDINATE_JITTER_KM)
        jy = rng.uniform(-COORDINATE_JITTER_KM, COORDINATE_JITTER_KM)
        lat, lon = _km_to_latlon(x_km + jx, y_km + jy)
        coords[node_id] = (lat, lon)
        nodes.append({"node_id": node_id, "name": name, "latitude": lat,
                      "longitude": lon, "node_type": node_type})

    low_u, high_u = BASELINE_UTILIZATION_RANGE
    edges: list[dict[str, Any]] = []
    for a, b, road_type in ROAD_LINKS:
        profile = ROAD_TYPE_PROFILES[road_type]
        straight = haversine_km(*coords[a], *coords[b])
        detour = rng.uniform(profile.detour_factor_min, profile.detour_factor_max)
        distance = _ceil_to(straight * detour, 3)
        base_time = _ceil_to(distance / profile.nominal_speed_kmh * 60.0, 2)
        for src, dst in ((a, b), (b, a)):
            count = int(profile.default_capacity_vph * rng.uniform(low_u, high_u))
            edges.append({
                "edge_id": f"E{len(edges) + 1:03d}",
                "source": src,
                "destination": dst,
                "distance_km": distance,
                "base_travel_time_min": base_time,
                "capacity_vehicles_per_hour": profile.default_capacity_vph,
                "current_vehicle_count": count,
                "road_type": road_type,
            })

    return {
        "schema_version": SCENARIO_SCHEMA_VERSION,
        "scenario_id": "baseline",
        "description": "Milestone 1 baseline: 22-node synthetic city with an east-west trunk "
                       "corridor, arterial alternatives and local streets.",
        "data_provenance": PROVENANCE,
        "seed": seed,
        "assumptions": {
            "units": {"distance": "km", "time": "minutes", "capacity": "vehicles per hour"},
            "network_max_speed_kmh": NETWORK_MAX_SPEED_KMH,
            "congestion_model": {
                "formula": "u = count/capacity; if u<=1: m = 1 + alpha*u^beta; "
                           "else: m = 1 + alpha + overload_slope*(u-1); time = base_time*m",
                "parameters": DEFAULT_CONGESTION.to_dict(),
                "note": "alpha/beta are classic BPR values; overload_slope is a project assumption.",
            },
            "road_type_profiles": {k: v.to_dict() for k, v in ROAD_TYPE_PROFILES.items()},
            "baseline_utilization_range": list(BASELINE_UTILIZATION_RANGE),
            "coordinate_jitter_km": COORDINATE_JITTER_KM,
            "coordinate_anchor": {"latitude": SYNTHETIC_ANCHOR_LAT, "longitude": SYNTHETIC_ANCHOR_LON,
                                  "note": "Arbitrary anchor; not a real city."},
            "a_star_heuristic": "straight-line km / network_max_speed_kmh * 60 * 0.999 (admissible)",
        },
        "simulation": {"start_time_min": 0.0},
        "nodes": nodes,
        "edges": edges,
    }


def build_synthetic_city(seed: int = DEFAULT_SEED) -> LoadedScenario:
    return scenario_from_dict(generate_synthetic_city_dict(seed))
